### ISSUE TITLE
cannot receive all entities 

### ISSUE THREAD

**Issue by chanthou** [TinderBox/dynamics_crm#39]
Hi all, 
When I try to get all CRM entities it doesn't respond array of entities 
@client.retrieve_all_entities()   

> {"ResponseName"=>"RetrieveAllEntities", "Timestamp"=>"1956489052"}

**Comment by jheth** [comment]
@chanthou That call returns a `Response` object, which contains an `entities` attribute

```ruby
response = @client.retrieve_all_entities()
entities = response.entities.collect{|entity|
   [entity.SchemaName, entity.LogicalName]
}
```

**Comment by jheth** [comment]
@chanthou Did my comment resolve your issue?

**Comment by jheth** [comment]
I'm marking this resolved. We can reopen if needed.
