### ISSUE TITLE
Setting state on entities?

### ISSUE THREAD

**Issue by mbhnyc** [TinderBox/dynamics_crm#47]
Hey all-

Is it possible to set entity state with the gem currently, docs suggest it should be editable after creation, but point to the `https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.setstaterequest.aspx` method which i don't think we support yet. 

Is this possible in a different way?  Can start on a pull request to support this function, just wanted to know if i was missing anything dumb.

**Comment by mbhnyc** [comment]
I also have PR incoming to allow OR queries for entities... 💯

**Comment by mbhnyc** [comment]
ping!

**Comment by jheth** [comment]
Hey @mbhnyc.  From what I remember, `state` is different than other fields.  I have implemented the WinOpportunity and LoseOpportunity which modify opportunity state, but I'm happy to accept a generic set state request.

**Comment by mbhnyc** [comment]
ah great, that's a good model to go by when i need to implement this, i'll see what i can do to make it generic thanks @jheth !
