### ISSUE TITLE
Accessing entities with guid only?

### ISSUE THREAD

**Issue by mbhnyc** [TinderBox/dynamics_crm#57]
I have a generic integration adapter that works for both salesforce and dynamics and one irritating thing is how in Dynamics i always need to supply a type and ID — is there a way to discover the type of an object?  It doesn't look like it from what I know so far, but thought I'd ask.

**Comment by jheth** [comment]
I agree. I have used the Salesforce ID to identify type before and I have not found a way to do the same with CRM.

**Comment by mbhnyc** [comment]
kk, so just sucks to be us 👎
